### ISSUE TITLE
[BUG] Intermittent error, unable to parse 'output.yaml':    "yaml.parser.ParserError: while parsing a block mapping" suspected related to  "codeSnip: |2"

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/analyzer-lsp#521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

Don't have the specific commit version now, was around ~2/29/2024

### Priority

Critical

### Current Behavior

I ran into an issue which I am am unable to reproduce.

I created a [small script](https://github.com/jwmatthews/kai/blob/jpa/notebooks/jpa/analysis_report/analyze_all.sh) to analyze 4 applications, then as I was parsing the output.yaml I ran into this error (Full Output at end of issue)

    python3 -c "import yaml; data = yaml.safe_load(open('./output.yaml'));"

     File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
        raise ParserError("while parsing a block mapping", self.marks[-1],
    yaml.parser.ParserError: while parsing a block mapping
      in "./output.yaml", line 238, column 11
    expected <block end>, but found '<scalar>'

This is the output.yaml that was generated:
https://gist.github.com/jwmatthews/33bb7e8426c2ee1557b481a7b11c7d60#file-output-yaml-L240

The referenced problem area is below
    
     - uri: file:///tmp/source-code/src/main/webapp/WEB-INF/web.xml
              message: "Replace `http://xmlns.jcp.org/xml/ns/javaee` with `https://jakarta.ee/xml/ns/jakartaee` and change the schema version number "
              codeSnip: |2
                1  <?xml version="1.0" encoding="UTF-8"?>
                2  <web-app version="3.1"
                3           xmlns="http://xmlns.jcp.org/xml/ns/javaee"
                4           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                5           xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd">
                6      <servlet>
                7          <servlet-name>Faces Servlet</servlet-name>
                8          <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
                9          <load-on-startup>1</load-on-startup>
               10      </servlet>
               11      <servlet-mapping>
               12          <servlet-name>Faces Servlet</servlet-name>
               13          <url-pattern>*.xhtml</url-pattern>
               14      </servlet-mapping>
               15      <session-config>
               16          <session-timeout>
               17              30
               18          </session-timeout>
               19      </session-config>
               20      <welcome-file-list>
               21          <welcome-file>greet.xhtml</welcome-file>
               22      </welcome-file-list>
               23  </web-app>

I suspected the ```codeSnip: |2``` was related, yet I'm seeing other runs that still contain this line and parse correctly. 
  
  

### Expected Behavior

No yaml parsing errors

### How Reproducible

Always (Default)

### Steps To Reproduce

I'm unable to consistently reproduce.  This happened once so far while I was scripting the steps for analyzing apps in Kai.
This is the script I created:
* https://github.com/jwmatthews/kai/blob/jpa/notebooks/jpa/analysis_report/analyze_all.sh

This specific commit has the full output and the analyze_all.sh I used to create the out output.yaml which failed to parse:
https://github.com/jwmatthews/kai/blob/e7c0972a014251e600151eb63882690a52443ccd/notebooks/jpa/analysis_report/greeter/output.yaml

### Environment

```markdown
- Running with Kantra, but I've seen upgraded the Kantra binary and don't have the specific version I was using.
```

### Anything else?

Below is a means of retrieving the output.yaml I was attempting to parse.
I have NOT been able to replicate generating a broken output.yaml from subsequent runs.  

`wget https://gist.githubusercontent.com/jwmatthews/33bb7e8426c2ee1557b481a7b11c7d60/raw/2586f968e65c1c01231b4247207d67c41633e66e/output.yaml`

    $ python3 -c "import yaml; data = yaml.safe_load(open('./output.yaml'));" 
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/__init__.py", line 125, in safe_load
        return load(stream, SafeLoader)
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
        return loader.get_single_data()
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/constructor.py", line 49, in get_single_data
        node = self.get_single_node()
               ^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/composer.py", line 36, in get_single_node
        document = self.compose_document()
                   ^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/composer.py", line 55, in compose_document
        node = self.compose_node(None, None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/composer.py", line 82, in compose_node
        node = self.compose_sequence_node(anchor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/composer.py", line 111, in compose_sequence_node
        node.value.append(self.compose_node(node, index))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/composer.py", line 133, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/composer.py", line 133, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/composer.py", line 133, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/composer.py", line 82, in compose_node
        node = self.compose_sequence_node(anchor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/composer.py", line 111, in compose_sequence_node
        node.value.append(self.compose_node(node, index))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/composer.py", line 127, in compose_mapping_node
        while not self.check_event(MappingEndEvent):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/parser.py", line 98, in check_event
        self.current_event = self.state()
                             ^^^^^^^^^^^^
      File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.11/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
        raise ParserError("while parsing a block mapping", self.marks[-1],
    yaml.parser.ParserError: while parsing a block mapping
      in "./output.yaml", line 238, column 11
    expected <block end>, but found '<scalar>'
      in "./output.yaml", line 250, column 12

**Comment by jwmatthews** [comment]
Thank you to @aufi for sharing the below info with me:

As per:  https://alisoftware.github.io/yaml/2021/08/19/yaml-part2-strings/#multi-line-blocks-and-long-strings
> Indentation in multi-line blocks
> In a multi-line block, YAML first determines the indentation level of the whole block:
> 
> - Either by guessing it from the number of leading spaces of the first non-empty line, if you don’t specify anything (most common case)
> - Or by using the explicit value you provide after the | or >, to indicate the number of additional spaces compared to the parent node.


So at this point, I don't believe the use of "|2" is the problem. 

I have not seen this occur again and I'm unable to reproduce.
I think best course is to close this issue for now, if I run into this again I will reopen this issue.
